### ISSUE TITLE
OS/2: ySubscriptYOffset and ySuperscriptYOffset

### ISSUE THREAD

**Issue by andrestelex** [vv-monsalve/Caladea#4]
I would increase the values.
Is set to 75, but I think it needs more for a superscript or subscript to stand out. At least 100.

75 vs 100
![image](https://user-images.githubusercontent.com/5502786/70472893-d904b580-1ac7-11ea-8469-953abb34d12c.png)

**Comment by andrestelex** [comment]
https://docs.microsoft.com/en-us/typography/opentype/spec/os2#ysubscriptyoffset

I would also set the ySubscriptXOffset to 0 in all fonts (is different in italics)

**Comment by vv-monsalve** [comment]
The current values came from the original design so were respected as it. SubscriptYOffset and SubscriptXOffset were now changed to the indicated values.
