### ISSUE TITLE
OS/2: Panose values

### ISSUE THREAD

**Issue by andrestelex** [vv-monsalve/Caladea#5]
Not a fan of Panose, but the weight value should be different between Rg and Bd and also in italics.

https://forum.high-logic.com/postedfiles/Panose.pdf

For weight (bit 3)
Rg: 5
Bd: 8

For italics (bit 8, lettershape)
9

On GlyphsApp, they can be set adding a custom parameter on each instance, and the main entry under "font" should be deleted. Otherwise it can be hardcoded directly into UFOs (but I'm not sure about what's best for the workflow)

![image](https://user-images.githubusercontent.com/5502786/70473742-8cba7500-1ac9-11ea-8d8a-783e59c6b1d1.png)

**Comment by vv-monsalve** [comment]
Thanks. Not a fan of Panose either, the values came from the original source files, probably after the migration from Fontlab and remained in the font information for the first master of the file. They were now changed as suggested.
