### ISSUE TITLE
Basic OT features?

### ISSUE THREAD

**Issue by andrestelex** [vv-monsalve/Caladea#7]
Some glyphs are present in the font, but there is no feature to make them accesible.

I would add these features

sups (basic superscript)
frac (precomposed fractions)
ordn (ordinals ordfeminine ordmasculine)
liga (ligatures)
locl (dutch IJ ij, Ldot ldot for catalonian and romanian Scedilla Tcedilla)

Most of them can be extracted from other free fonts, such as Sarala
https://raw.githubusercontent.com/huertatipografica/sarala/master/font/Sarala-Regular.ufo/features.fea

**Comment by vv-monsalve** [comment]
solved
